var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MAYAUL\"><meta name=\"release\" content=\"2017\"><meta name=\"book\" content=\"Developer\"><meta name=\"created\" content=\"2016-06-16\"><meta name=\"topicid\" content=\"GUID-02DEF634-1E7B-48C6-8ACD-2C934CA97887\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>MPassContext Class Reference</title>\n\
   \n\
\n\
<meta name=\"topic-subtype\" content=\"C++\"></head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'class_m_h_w_render_1_1_m_pass_context.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>MPassContext Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/classes.html\"><span>Class&#160;Index</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  \n\
  <div class=\"headertitle\">\n\
<div class=\"title\">MPassContext Class Reference<div class=\"ingroups\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/group___open_maya_render.html\">OpenMayaRender - API module for rendering</a></div></div>  </div>\n\
<div id=\"OverviewLinksDiv\"><div id=\"dynsection-overview\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\"><img id=\"dynsection-overview-trigger\" src=\"cpp_ref/closed.png\" alt=\"+\"> Related help topics: </div><div id=\"dynsection-overview-content\" class=\"dyncontent\" style=\"display:none;\"><ul class=\"overviewLinks\">\n\
<li class=\"overviewLink\"><a href=\"#!/url=./files/GUID-653104AC-D0E8-490F-AF00-71DEB76139A4.htm\">What\'s New / What\'s Changed? &gt; What\'s New in API in Maya 2016 Extension 2</a></li>\n\
<li class=\"overviewLink\"><a href=\"#!/url=./files/GUID-6644CF46-6648-45B8-A3D8-76EDD7712571.htm\">What\'s New / What\'s Changed? &gt; What\'s New in API in Maya 2016</a></li>\n\
<li class=\"overviewLink\"><a href=\"#!/url=./files/GUID-1BB599DB-D637-4D95-AD35-9F85AA5A35ED.htm\">What\'s New / What\'s Changed? &gt; What\'s New in API in Maya 2016 &gt; C++ API Changes in Maya 2016</a></li>\n\
<li class=\"overviewLink\"><a href=\"#!/url=./files/GUID-DBDCB848-B0A5-4256-912C-6FCE25D12984.htm\">What\'s New / What\'s Changed? &gt; Autodesk Maya 2015</a></li>\n\
<li class=\"overviewLink\"><a href=\"#!/url=./files/GUID-9DBD7E49-7A17-4CEB-89AF-A3B509AD91E2.htm\">What\'s New / What\'s Changed? &gt; Autodesk Maya 2014</a></li>\n\
<li class=\"overviewLink\"><a href=\"#!/url=./files/GUID-F0CA7A2C-EE99-4A95-9E5E-C187F000092C.htm\">What\'s New / What\'s Changed? &gt; Extension for Autodesk Maya 2013</a></li>\n\
<li class=\"overviewLink\"><a href=\"#!/url=./files/GUID-9B9CDD21-F3AD-4B79-B610-AAA42D4C6599.htm\">Viewport 2.0 API &gt; Maya Viewport 2.0 API Guide &gt; API constructs &gt; Frame and draw contexts</a></li>\n\
<li class=\"overviewLink\"><a href=\"#!/url=./files/GUID-D1853655-D22D-4B1C-8CBD-528CD1903B0E.htm\">Viewport 2.0 API &gt; Maya Viewport 2.0 API Guide &gt; Advanced Topics &gt; Lighting Interfaces</a></li>\n\
<li class=\"overviewLink\"><a href=\"#!/url=./files/GUID-E171DC25-5750-4CA0-9A6C-A411EED1CE3E.htm\">Viewport 2.0 API &gt; Maya Viewport 2.0 API Guide &gt; Advanced Topics &gt; Effects interfaces</a></li>\n\
<li class=\"overviewLink\"><a href=\"#!/url=./files/GUID-A2E52A98-EA6D-48DB-B566-C53C1F3BA9D8.htm\">Viewport 2.0 API &gt; Maya Viewport 2.0 API Guide &gt; Advanced Topics &gt; Profile Viewport 2.0 rendering events</a></li>\n\
<li class=\"overviewLink\"><a href=\"#!/url=./files/GUID-13229A83-B6A0-4280-840C-F9C6F40BB13D.htm\">Viewport 2.0 API &gt; Semantics and annotations supported by the dx11Shader and glslShader plug-ins in Viewport 2.0</a></li>\n\
</ul></div></div>\n\
<div class=\"summary\">\n\
<a href=\"class_m_h_w_render_1_1_m_pass_context.html#pub-methods\">Public Member Functions</a> &#124;\n\
<a href=\"class_m_h_w_render_1_1_m_pass_context.html#pub-static-attribs\">Static Public Attributes</a>  </div></div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;MDrawContext.h&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><p>Class to allow access to pass context information. </p>\n\
<p><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html\" title=\"Class to allow access to pass context information. \">MPassContext</a> provides access to current pass context information. The term \"pass context\" is used to denote a logical breakdown of the render loop within a single frame to render.</p>\n\
<p>A \"pass\" denotes the highest level elements of the breakdown. Each pass has a unique identifier and a list of semantics.</p>\n\
<p>The identifier can either be an internally specified identifier or the name of a custom scene or user render operation (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_scene_render.html\" title=\"Class which defines a scene render. \">MSceneRender</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_user_render_operation.html\" title=\"Class which defines a user defined rendering operation. \">MUserRenderOperation</a> respectively).</p>\n\
<p>The semantics provide a description of what is being rendered. The list of semantics is ordered, from first to last element, such that the first element provides the broadest description and additional elements refine (provides additional details) about the previous element.</p>\n\
<p>The following is a list of semantics which may be returned as the first element of the semantic list. Possible refining semantics are also described. </p><ul>\n\
<li>\n\
A \"color pass\" semantic implies rendering for color output. Rendering for a color pass can be further broken down into the follow logical categorizations: <ul>\n\
<li>\n\
Color drawing of opaque surfaces. For this, an additional semantic can describe if a material override is being used. </li>\n\
<li>\n\
Color drawing of transparent surfaces. For this, a breakdown of whether the drawing is occurring with back or front-face culling may be specified. </li>\n\
<li>\n\
Color drawing of the UI for surfaces. </li>\n\
</ul>\n\
</li>\n\
<li>\n\
A \"shadow pass\" semantic implies rendering to create a shadow map. </li>\n\
<li>\n\
A \"depth\" pass semantic implies rendering for depth output only and not color. </li>\n\
<li>\n\
A \"depth and normal\" semantic implies rendering of depth and object normals as output. </li>\n\
<li>\n\
A \"user pass\" semantic implies that a user operation (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_user_render_operation.html\" title=\"Class which defines a user defined rendering operation. \">MUserRenderOperation</a>) is the current operation being executed for the active render override (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_render_override.html\" title=\"Base class for defining a rendering override. \">MRenderOverride</a>) </li>\n\
</ul>\n\
<p>As an example, the semantic list returned may contain these elements:</p>\n\
<p>[ color pass, opaque surface drawing, material override ]</p>\n\
<p>This indicates that the active pass is drawing to a color output. Also that the render items being draw are opaque, and that those render items are being drawing with a material override.</p>\n\
<p>As a second example, the semantic list returned may contain these elements:</p>\n\
<p>[ color pass, transparent surface drawing, back-face culling ]</p>\n\
<p>This means that the active pass is drawing to a color output. Also that the render items being drawn are transparent, and that those render items are being drawing with back-face culling enabled. </p>\n\
<dl class=\"section \"><div id=\"dynsection-example0\" class=\"dynheader closed\" onclick=\"return toggleVisibility(this)\" style=\"cursor:pointer;\"><dt><img id=\"dynsection-example0-trigger\" src=\"cpp_ref/closed.png\" alt=\"+\"> <b>Examples: </b></dt></div><div id=\"dynsection-example0-content\" class=\"dyncontent\" style=\"display:none;\"><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/api_mesh_shape_2api_mesh_geometry_override_8cpp-example.html#_a13\">apiMeshShape/apiMeshGeometryOverride.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/blast2_cmd_2blast2_cmd_8cpp-example.html#_a15\">blast2Cmd/blast2Cmd.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/cg_fx_2cgfx_shader_node_8cpp-example.html#_a156\">cgFx/cgfxShaderNode.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/custom_texture_shader_2custom_texture_shader_override_8cpp-example.html#_a17\">customTextureShader/customTextureShaderOverride.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/dx11_shader_2dx11_shader_8cpp-example.html#_a155\">dx11Shader/dx11Shader.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/dx11_shader_2dx11_shader_override_8cpp-example.html#_a12\">dx11Shader/dx11ShaderOverride.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/glsl_shader_2_g_l_s_l_shader_8cpp-example.html#_a289\">glslShader/GLSLShader.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/gpu_cache_2gpu_cache_draw_override_8cpp-example.html#_a41\">gpuCache/gpuCacheDrawOverride.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/hw_phong_shader_2hw_phong_shader_8cpp-example.html#_a47\">hwPhongShader/hwPhongShader.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/rawfoot_print_node_2rawfoot_print_node_8cpp-example.html#_a215\">rawfootPrintNode/rawfootPrintNode.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/swiss_army_manip_2swiss_army_manip_8cpp-example.html#_a113\">swissArmyManip/swissArmyManip.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/view_render_override_2view_render_override_operations_8cpp-example.html#_a121\">viewRenderOverride/viewRenderOverrideOperations.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/view_render_override_2view_render_override_user_operation_8cpp-example.html#_a41\">viewRenderOverride/viewRenderOverrideUserOperation.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/view_render_override_shadows_2view_render_override_shadows_8cpp-example.html#_a26\">viewRenderOverrideShadows/viewRenderOverrideShadows.cpp</a>, and <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/view_render_override_targets_2view_render_override_targets_8cpp-example.html#_a24\">viewRenderOverrideTargets/viewRenderOverrideTargets.cpp</a>.</dd></div>\n\
</dl></div><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:ae90d4b4c8175e81800d8eb16ee126e1f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#ae90d4b4c8175e81800d8eb16ee126e1f\">passIdentifier</a> () const </td></tr>\n\
<tr class=\"memdesc:ae90d4b4c8175e81800d8eb16ee126e1f\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Return the identifier for the pass context.  <a href=\"class_m_h_w_render_1_1_m_pass_context.html#ae90d4b4c8175e81800d8eb16ee126e1f\">More...</a><br></td></tr>\n\
<tr class=\"separator:ae90d4b4c8175e81800d8eb16ee126e1f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9737189d5cfffd795336d711a678d627\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string_array.html\">MStringArray</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a9737189d5cfffd795336d711a678d627\">passSemantics</a> () const </td></tr>\n\
<tr class=\"memdesc:a9737189d5cfffd795336d711a678d627\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Return an array of semantics for the pass context.  <a href=\"class_m_h_w_render_1_1_m_pass_context.html#a9737189d5cfffd795336d711a678d627\">More...</a><br></td></tr>\n\
<tr class=\"separator:a9737189d5cfffd795336d711a678d627\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a54cb1ff5e4a10ffc51cb05ddab8e69ab\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a54cb1ff5e4a10ffc51cb05ddab8e69ab\">hasShaderOverride</a> () const </td></tr>\n\
<tr class=\"memdesc:a54cb1ff5e4a10ffc51cb05ddab8e69ab\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Return if there is a shader instance override set for the current pass.  <a href=\"class_m_h_w_render_1_1_m_pass_context.html#a54cb1ff5e4a10ffc51cb05ddab8e69ab\">More...</a><br></td></tr>\n\
<tr class=\"separator:a54cb1ff5e4a10ffc51cb05ddab8e69ab\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aef8d7620ddd58e44e45ea0f0dfaa6fb4\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_shader_instance.html\">MShaderInstance</a> *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#aef8d7620ddd58e44e45ea0f0dfaa6fb4\">shaderOverrideInstance</a> () const </td></tr>\n\
<tr class=\"memdesc:aef8d7620ddd58e44e45ea0f0dfaa6fb4\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Return the shader instance override set for the current pass.  <a href=\"class_m_h_w_render_1_1_m_pass_context.html#aef8d7620ddd58e44e45ea0f0dfaa6fb4\">More...</a><br></td></tr>\n\
<tr class=\"separator:aef8d7620ddd58e44e45ea0f0dfaa6fb4\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-static-attribs\"></a>\n\
Static Public Attributes</h2></td></tr>\n\
<tr class=\"memitem:a97ffcfc5e6c4bd512eab6727c58a9ae8\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a97ffcfc5e6c4bd512eab6727c58a9ae8\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a97ffcfc5e6c4bd512eab6727c58a9ae8\">kColorPassSemantic</a></td></tr>\n\
<tr class=\"memdesc:a97ffcfc5e6c4bd512eab6727c58a9ae8\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for a color pass. <br></td></tr>\n\
<tr class=\"separator:a97ffcfc5e6c4bd512eab6727c58a9ae8\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab0d481f367db0fa41c2b3a1aeb2074c8\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"ab0d481f367db0fa41c2b3a1aeb2074c8\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#ab0d481f367db0fa41c2b3a1aeb2074c8\">kShadowPassSemantic</a></td></tr>\n\
<tr class=\"memdesc:ab0d481f367db0fa41c2b3a1aeb2074c8\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for a shadow pass. <br></td></tr>\n\
<tr class=\"separator:ab0d481f367db0fa41c2b3a1aeb2074c8\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a67e11eaab888b31695e3bc19dc1c26ef\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a67e11eaab888b31695e3bc19dc1c26ef\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a67e11eaab888b31695e3bc19dc1c26ef\">kDepthPassSemantic</a></td></tr>\n\
<tr class=\"memdesc:a67e11eaab888b31695e3bc19dc1c26ef\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for a depth pass, which pre-renders an intermediate normalized depth target and a linear depth texture that can be used for depth testing during later passes. <br></td></tr>\n\
<tr class=\"separator:a67e11eaab888b31695e3bc19dc1c26ef\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a30804db03c6cccf4fd8d480fe4af0660\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a30804db03c6cccf4fd8d480fe4af0660\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a30804db03c6cccf4fd8d480fe4af0660\">kNormalDepthPassSemantic</a></td></tr>\n\
<tr class=\"memdesc:a30804db03c6cccf4fd8d480fe4af0660\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for a normal and depth pass, whose result will be used for SSAO. <br></td></tr>\n\
<tr class=\"separator:a30804db03c6cccf4fd8d480fe4af0660\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:adb72fdd740b1a4bbfcf963fa08703dab\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"adb72fdd740b1a4bbfcf963fa08703dab\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#adb72fdd740b1a4bbfcf963fa08703dab\">kOpaqueGeometrySemantic</a></td></tr>\n\
<tr class=\"memdesc:adb72fdd740b1a4bbfcf963fa08703dab\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic to indicate opaque surfaces are being drawn. <br></td></tr>\n\
<tr class=\"separator:adb72fdd740b1a4bbfcf963fa08703dab\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2853efc53f04d372684cb613c0839d5d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a2853efc53f04d372684cb613c0839d5d\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a2853efc53f04d372684cb613c0839d5d\">kPreUIGeometrySemantic</a></td></tr>\n\
<tr class=\"memdesc:a2853efc53f04d372684cb613c0839d5d\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic to indicate pre-scene UI is being drawn. E.g. The grid. <br></td></tr>\n\
<tr class=\"separator:a2853efc53f04d372684cb613c0839d5d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a702cd344fc5a426244be54df81e24cae\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a702cd344fc5a426244be54df81e24cae\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a702cd344fc5a426244be54df81e24cae\">kPostUIGeometrySemantic</a></td></tr>\n\
<tr class=\"memdesc:a702cd344fc5a426244be54df81e24cae\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic to indicate post-scene UI for surfaces is being drawn. e.g. the wireframe or components. <br></td></tr>\n\
<tr class=\"separator:a702cd344fc5a426244be54df81e24cae\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6c5d1bb1a7e64922c7db3af0bbb805df\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a6c5d1bb1a7e64922c7db3af0bbb805df\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a6c5d1bb1a7e64922c7db3af0bbb805df\">kUIGeometrySemantic</a></td></tr>\n\
<tr class=\"memdesc:a6c5d1bb1a7e64922c7db3af0bbb805df\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic to indicate UI for surfaces is being drawn. e.g. the wireframe or components. <br></td></tr>\n\
<tr class=\"separator:a6c5d1bb1a7e64922c7db3af0bbb805df\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a97ae5331e1466c51fc35b434c5e46601\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a97ae5331e1466c51fc35b434c5e46601\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a97ae5331e1466c51fc35b434c5e46601\">kOpaqueUISemantic</a></td></tr>\n\
<tr class=\"memdesc:a97ae5331e1466c51fc35b434c5e46601\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for opaque UI. <br></td></tr>\n\
<tr class=\"separator:a97ae5331e1466c51fc35b434c5e46601\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a065de49d1b4977f6a82b4ab0fbee53ca\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a065de49d1b4977f6a82b4ab0fbee53ca\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a065de49d1b4977f6a82b4ab0fbee53ca\">kTransparentUISemantic</a></td></tr>\n\
<tr class=\"memdesc:a065de49d1b4977f6a82b4ab0fbee53ca\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for transparent UI. <br></td></tr>\n\
<tr class=\"separator:a065de49d1b4977f6a82b4ab0fbee53ca\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afa0943a269c9a0c85a5d4cb0d14a4b0c\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"afa0943a269c9a0c85a5d4cb0d14a4b0c\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#afa0943a269c9a0c85a5d4cb0d14a4b0c\">kXrayUISemantic</a></td></tr>\n\
<tr class=\"memdesc:afa0943a269c9a0c85a5d4cb0d14a4b0c\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for UI in xray mode. <br></td></tr>\n\
<tr class=\"separator:afa0943a269c9a0c85a5d4cb0d14a4b0c\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a5d97dca0f38fda2f0993548ef576e664\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a5d97dca0f38fda2f0993548ef576e664\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a5d97dca0f38fda2f0993548ef576e664\">kTransparentGeometrySemantic</a></td></tr>\n\
<tr class=\"memdesc:a5d97dca0f38fda2f0993548ef576e664\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic to indicate transparent surfaces are being drawn. <br></td></tr>\n\
<tr class=\"separator:a5d97dca0f38fda2f0993548ef576e664\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a99397c595d39f3decd87dfb85faf16a9\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a99397c595d39f3decd87dfb85faf16a9\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a99397c595d39f3decd87dfb85faf16a9\">kCullBackSemantic</a></td></tr>\n\
<tr class=\"memdesc:a99397c595d39f3decd87dfb85faf16a9\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic to indicate that back-face culling is being applied. <br></td></tr>\n\
<tr class=\"separator:a99397c595d39f3decd87dfb85faf16a9\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6715518f047f0e552636b74d311dfffd\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a6715518f047f0e552636b74d311dfffd\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a6715518f047f0e552636b74d311dfffd\">kCullFrontSemantic</a></td></tr>\n\
<tr class=\"memdesc:a6715518f047f0e552636b74d311dfffd\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic to indicate that front-face culling is being applied. <br></td></tr>\n\
<tr class=\"separator:a6715518f047f0e552636b74d311dfffd\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aeab00787a25fdaf547b7dccd9af7cf8e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"aeab00787a25fdaf547b7dccd9af7cf8e\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#aeab00787a25fdaf547b7dccd9af7cf8e\">kMaterialOverrideSemantic</a></td></tr>\n\
<tr class=\"memdesc:aeab00787a25fdaf547b7dccd9af7cf8e\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic to indicate that a material override is being used. <br></td></tr>\n\
<tr class=\"separator:aeab00787a25fdaf547b7dccd9af7cf8e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9160078f7d16515ce7b689a7e0356c90\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a9160078f7d16515ce7b689a7e0356c90\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a9160078f7d16515ce7b689a7e0356c90\">kTransparentPeelSemantic</a></td></tr>\n\
<tr class=\"memdesc:a9160078f7d16515ce7b689a7e0356c90\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for a transparent peel pass. <br></td></tr>\n\
<tr class=\"separator:a9160078f7d16515ce7b689a7e0356c90\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad9f3e908d48e77144e99c804074485b1\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"ad9f3e908d48e77144e99c804074485b1\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#ad9f3e908d48e77144e99c804074485b1\">kTransparentPeelAndAvgSemantic</a></td></tr>\n\
<tr class=\"memdesc:ad9f3e908d48e77144e99c804074485b1\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for a transparent peel-and-average pass. <br></td></tr>\n\
<tr class=\"separator:ad9f3e908d48e77144e99c804074485b1\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a70c9d0658fe61e3154bb60cb40daf2a2\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a70c9d0658fe61e3154bb60cb40daf2a2\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a70c9d0658fe61e3154bb60cb40daf2a2\">kTransparentWeightedAvgSemantic</a></td></tr>\n\
<tr class=\"memdesc:a70c9d0658fe61e3154bb60cb40daf2a2\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for a transparent weighted-average pass. <br></td></tr>\n\
<tr class=\"separator:a70c9d0658fe61e3154bb60cb40daf2a2\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa596d88abf6f7abf27c45aed0532907f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"aa596d88abf6f7abf27c45aed0532907f\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#aa596d88abf6f7abf27c45aed0532907f\">kUserPassSemantic</a></td></tr>\n\
<tr class=\"memdesc:aa596d88abf6f7abf27c45aed0532907f\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic to indicate a user defined pass (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_user_render_operation.html\" title=\"Class which defines a user defined rendering operation. \">MUserRenderOperation</a>) <br></td></tr>\n\
<tr class=\"separator:aa596d88abf6f7abf27c45aed0532907f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad934a68929f94a0353d31cf5037edebf\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"ad934a68929f94a0353d31cf5037edebf\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#ad934a68929f94a0353d31cf5037edebf\">kBeginRenderSemantic</a></td></tr>\n\
<tr class=\"memdesc:ad934a68929f94a0353d31cf5037edebf\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic to indicate the start of rendering. See <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_renderer.html#a837772824ffc712480bbd5e1d6fc355d\" title=\"Add a notification callback to the rendering pipeline. \">MRenderer::addNotification()</a> for usage. <br></td></tr>\n\
<tr class=\"separator:ad934a68929f94a0353d31cf5037edebf\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac014667cd1015f6ed2723003b2a8573e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"ac014667cd1015f6ed2723003b2a8573e\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#ac014667cd1015f6ed2723003b2a8573e\">kBeginSceneRenderSemantic</a></td></tr>\n\
<tr class=\"memdesc:ac014667cd1015f6ed2723003b2a8573e\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic to indicate the beginning of scene draw pass. See <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_renderer.html#a837772824ffc712480bbd5e1d6fc355d\" title=\"Add a notification callback to the rendering pipeline. \">MRenderer::addNotification()</a> for usage. <br></td></tr>\n\
<tr class=\"separator:ac014667cd1015f6ed2723003b2a8573e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a73be45b2fb0d7ad17652f9a0f98baa67\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a73be45b2fb0d7ad17652f9a0f98baa67\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a73be45b2fb0d7ad17652f9a0f98baa67\">kEndSceneRenderSemantic</a></td></tr>\n\
<tr class=\"memdesc:a73be45b2fb0d7ad17652f9a0f98baa67\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic to indicate the end of a scene draw pass. See <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_renderer.html#a837772824ffc712480bbd5e1d6fc355d\" title=\"Add a notification callback to the rendering pipeline. \">MRenderer::addNotification()</a> for usage. <br></td></tr>\n\
<tr class=\"separator:a73be45b2fb0d7ad17652f9a0f98baa67\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a780076ccaa2af55f6023c67eaed79fae\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a780076ccaa2af55f6023c67eaed79fae\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a780076ccaa2af55f6023c67eaed79fae\">kEndRenderSemantic</a></td></tr>\n\
<tr class=\"memdesc:a780076ccaa2af55f6023c67eaed79fae\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic to indicate the end of rendering. See <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_renderer.html#a837772824ffc712480bbd5e1d6fc355d\" title=\"Add a notification callback to the rendering pipeline. \">MRenderer::addNotification()</a> for usage. <br></td></tr>\n\
<tr class=\"separator:a780076ccaa2af55f6023c67eaed79fae\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a728fc00f0764227a6f345c089058c998\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a728fc00f0764227a6f345c089058c998\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a728fc00f0764227a6f345c089058c998\">kSelectionPassSemantic</a></td></tr>\n\
<tr class=\"memdesc:a728fc00f0764227a6f345c089058c998\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for a selection pass. <br></td></tr>\n\
<tr class=\"separator:a728fc00f0764227a6f345c089058c998\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a730755c181d1c16d7abde72c447fac04\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a730755c181d1c16d7abde72c447fac04\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a730755c181d1c16d7abde72c447fac04\">kDOFPassSemantic</a></td></tr>\n\
<tr class=\"memdesc:a730755c181d1c16d7abde72c447fac04\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for depth-of-field pass. <br></td></tr>\n\
<tr class=\"separator:a730755c181d1c16d7abde72c447fac04\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2781bebea5ef7c30f94bda5bf9c38a36\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a2781bebea5ef7c30f94bda5bf9c38a36\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a2781bebea5ef7c30f94bda5bf9c38a36\">kMotionVectorPassSemantic</a></td></tr>\n\
<tr class=\"memdesc:a2781bebea5ef7c30f94bda5bf9c38a36\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for motion vector pass, whose result will be used for motion blur. <br></td></tr>\n\
<tr class=\"separator:a2781bebea5ef7c30f94bda5bf9c38a36\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a21eddbaf1720cec960972c79d2cde72a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a21eddbaf1720cec960972c79d2cde72a\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a21eddbaf1720cec960972c79d2cde72a\">kPEPatternPassSemantic</a></td></tr>\n\
<tr class=\"memdesc:a21eddbaf1720cec960972c79d2cde72a\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for post-effect pattern pass, which fills an intermediate depth target with depth values of surfaces included in post effects. The depth target will be used for depth test in non-post-effect pattern pass later. <br></td></tr>\n\
<tr class=\"separator:a21eddbaf1720cec960972c79d2cde72a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8f503e129a06c3b3e69d38572579cf63\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"anchor\" id=\"a8f503e129a06c3b3e69d38572579cf63\"></a>\n\
static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_pass_context.html#a8f503e129a06c3b3e69d38572579cf63\">kNonPEPatternPassSemantic</a></td></tr>\n\
<tr class=\"memdesc:a8f503e129a06c3b3e69d38572579cf63\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Semantic for non-post-effect pattern pass, which produces alpha mask for surfaces excluded from post effects in order to composite the beauty pass output without post effects over the one with post effects later. <br></td></tr>\n\
<tr class=\"separator:a8f503e129a06c3b3e69d38572579cf63\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"ae90d4b4c8175e81800d8eb16ee126e1f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string.html\">MString</a> &amp; passIdentifier </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Return the identifier for the pass context. </p>\n\
<p>If a render override is active, then the name of the current operation will be returned.</p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>identifier string </dd></dl>\n\
<dl class=\"section \"><div id=\"dynsection-example1\" class=\"dynheader closed\" onclick=\"return toggleVisibility(this)\" style=\"cursor:pointer;\"><dt><img id=\"dynsection-example1-trigger\" src=\"cpp_ref/closed.png\" alt=\"+\"> <b>Examples: </b></dt></div><div id=\"dynsection-example1-content\" class=\"dyncontent\" style=\"display:none;\"><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/api_mesh_shape_2api_mesh_geometry_override_8cpp-example.html#a15\">apiMeshShape/apiMeshGeometryOverride.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/blast2_cmd_2blast2_cmd_8cpp-example.html#a17\">blast2Cmd/blast2Cmd.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/cg_fx_2cgfx_shader_node_8cpp-example.html#a158\">cgFx/cgfxShaderNode.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/dx11_shader_2dx11_shader_override_8cpp-example.html#a14\">dx11Shader/dx11ShaderOverride.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/gpu_cache_2gpu_cache_draw_override_8cpp-example.html#a44\">gpuCache/gpuCacheDrawOverride.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/hw_phong_shader_2hw_phong_shader_8cpp-example.html#a49\">hwPhongShader/hwPhongShader.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/rawfoot_print_node_2rawfoot_print_node_8cpp-example.html#a218\">rawfootPrintNode/rawfootPrintNode.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/view_render_override_2view_render_override_operations_8cpp-example.html#a123\">viewRenderOverride/viewRenderOverrideOperations.cpp</a>, and <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/view_render_override_2view_render_override_user_operation_8cpp-example.html#a43\">viewRenderOverride/viewRenderOverrideUserOperation.cpp</a>.</dd></div>\n\
</dl>\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a9737189d5cfffd795336d711a678d627\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_string_array.html\">MStringArray</a> &amp; passSemantics </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Return an array of semantics for the pass context. </p>\n\
<p>The array may contain the following semantics: </p><ul>\n\
<li>\n\
MPassContext::colorPassSemantic : Indicates a color pass. </li>\n\
<li>\n\
MPassContext::shadowPassSemantic : Indicates a shadow map pass. </li>\n\
</ul>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>semantic string array </dd></dl>\n\
<dl class=\"section \"><div id=\"dynsection-example2\" class=\"dynheader closed\" onclick=\"return toggleVisibility(this)\" style=\"cursor:pointer;\"><dt><img id=\"dynsection-example2-trigger\" src=\"cpp_ref/closed.png\" alt=\"+\"> <b>Examples: </b></dt></div><div id=\"dynsection-example2-content\" class=\"dyncontent\" style=\"display:none;\"><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/api_mesh_shape_2api_mesh_geometry_override_8cpp-example.html#a17\">apiMeshShape/apiMeshGeometryOverride.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/blast2_cmd_2blast2_cmd_8cpp-example.html#a19\">blast2Cmd/blast2Cmd.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/cg_fx_2cgfx_shader_node_8cpp-example.html#a159\">cgFx/cgfxShaderNode.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/custom_texture_shader_2custom_texture_shader_override_8cpp-example.html#a20\">customTextureShader/customTextureShaderOverride.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/dx11_shader_2dx11_shader_8cpp-example.html#a157\">dx11Shader/dx11Shader.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/dx11_shader_2dx11_shader_override_8cpp-example.html#a16\">dx11Shader/dx11ShaderOverride.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/glsl_shader_2_g_l_s_l_shader_8cpp-example.html#a291\">glslShader/GLSLShader.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/gpu_cache_2gpu_cache_draw_override_8cpp-example.html#a46\">gpuCache/gpuCacheDrawOverride.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/hw_phong_shader_2hw_phong_shader_8cpp-example.html#a51\">hwPhongShader/hwPhongShader.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/rawfoot_print_node_2rawfoot_print_node_8cpp-example.html#a217\">rawfootPrintNode/rawfootPrintNode.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/swiss_army_manip_2swiss_army_manip_8cpp-example.html#a116\">swissArmyManip/swissArmyManip.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/view_render_override_2view_render_override_operations_8cpp-example.html#a124\">viewRenderOverride/viewRenderOverrideOperations.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/view_render_override_2view_render_override_user_operation_8cpp-example.html#a45\">viewRenderOverride/viewRenderOverrideUserOperation.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/view_render_override_shadows_2view_render_override_shadows_8cpp-example.html#a29\">viewRenderOverrideShadows/viewRenderOverrideShadows.cpp</a>, and <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/view_render_override_targets_2view_render_override_targets_8cpp-example.html#a27\">viewRenderOverrideTargets/viewRenderOverrideTargets.cpp</a>.</dd></div>\n\
</dl>\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a54cb1ff5e4a10ffc51cb05ddab8e69ab\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool hasShaderOverride </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Return if there is a shader instance override set for the current pass. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>true if override set </dd></dl>\n\
<dl class=\"section \"><div id=\"dynsection-example3\" class=\"dynheader closed\" onclick=\"return toggleVisibility(this)\" style=\"cursor:pointer;\"><dt><img id=\"dynsection-example3-trigger\" src=\"cpp_ref/closed.png\" alt=\"+\"> <b>Examples: </b></dt></div><div id=\"dynsection-example3-content\" class=\"dyncontent\" style=\"display:none;\"><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/custom_texture_shader_2custom_texture_shader_override_8cpp-example.html#a23\">customTextureShader/customTextureShaderOverride.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/dx11_shader_2dx11_shader_8cpp-example.html#a158\">dx11Shader/dx11Shader.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/glsl_shader_2_g_l_s_l_shader_8cpp-example.html#a408\">glslShader/GLSLShader.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/hw_phong_shader_2hw_phong_shader_8cpp-example.html#a55\">hwPhongShader/hwPhongShader.cpp</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/rawfoot_print_node_2rawfoot_print_node_8cpp-example.html#a219\">rawfootPrintNode/rawfootPrintNode.cpp</a>, and <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/swiss_army_manip_2swiss_army_manip_8cpp-example.html#a118\">swissArmyManip/swissArmyManip.cpp</a>.</dd></div>\n\
</dl>\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aef8d7620ddd58e44e45ea0f0dfaa6fb4\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_shader_instance.html\">MShaderInstance</a> * shaderOverrideInstance </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Return the shader instance override set for the current pass. </p>\n\
<p>When the returned new shader instance is no longer needed, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_m_h_w_render_1_1_m_shader_manager.html#a0c7deb55edc231cbb2365b271ecd55f8\" title=\"Deletes the MShaderInstance and releases its reference to the underlying shader which is held by the ...\">MShaderManager::releaseShader()</a> should be called to notify the shader manager that the caller is done with the shader.</p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>The shader override. </dd></dl>\n\
<dl class=\"section \"><div id=\"dynsection-example4\" class=\"dynheader closed\" onclick=\"return toggleVisibility(this)\" style=\"cursor:pointer;\"><dt><img id=\"dynsection-example4-trigger\" src=\"cpp_ref/closed.png\" alt=\"+\"> <b>Examples: </b></dt></div><div id=\"dynsection-example4-content\" class=\"dyncontent\" style=\"display:none;\"><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/rawfoot_print_node_2rawfoot_print_node_8cpp-example.html#a220\">rawfootPrintNode/rawfootPrintNode.cpp</a>, and <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/swiss_army_manip_2swiss_army_manip_8cpp-example.html#a121\">swissArmyManip/swissArmyManip.cpp</a>.</dd></div>\n\
</dl>\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following files:<ul>\n\
<li>MDrawContext.h</li>\n\
<li>MDrawContext.cpp</li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div><br></div>\n\
   </div></body>\n\
</html>\n\
";