var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>MRandom Namespace Reference</title>\n\
   \n\
\n\
<meta name=\"topic-subtype\" content=\"C++\"></head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'namespace_m_random.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>MRandom Namespace Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespace&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespacemembers.html\"><span>Namespace&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  \n\
  <div class=\"headertitle\">\n\
<div class=\"title\">MRandom Namespace Reference<div class=\"ingroups\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/group___open_maya.html\">OpenMaya - API module for common classes</a></div></div>  </div>\n\
<div id=\"OverviewLinksDiv\"><div id=\"dynsection-overview\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\"><img id=\"dynsection-overview-trigger\" src=\"cpp_ref/closed.png\" alt=\"+\"> Related help topics: </div><div id=\"dynsection-overview-content\" class=\"dyncontent\" style=\"display:none;\"><ul class=\"overviewLinks\">\n\
<li class=\"overviewLink\"><a href=\"#!/url=./developer/What-s-New-What-s-Changed-/What-s-New-in-API-in-Maya-2016.html\">What&#39;s New / What&#39;s Changed? &gt; What&#39;s New in API in Maya 2016 Extension 2</a></li>\n\
<li class=\"overviewLink\"><a href=\"#!/url=./developer/What-s-New-What-s-Changed-/What-s-New-in-API-in-Maya-2016/New-C-API-classes-in-Maya-2016.html\">What&#39;s New / What&#39;s Changed? &gt; What&#39;s New in API in Maya 2016 &gt; New C++ API classes in Maya 2016 Extension 2</a></li>\n\
</ul></div></div>\n\
<div class=\"summary\">\n\
<a href=\"namespace_m_random.html#func-members\">Functions</a>  </div></div><!--header-->\n\
<div class=\"contents\">\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Namespace description</h2>\n\
<div class=\"textblock\"><p>Methods for generating random numbers. </p>\n\
<p>The <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_m_random.html\" title=\"Methods for generating random numbers. \">MRandom</a> class implements several methods to generate sequences of random numbers.</p>\n\
<p>For a given fixed seed, input i produces the i\'th random number of a 2^64-long pseudo-random sequence. Different seeds will give different sequences, but nearby seeds may on rare occasion exhibit statistical correlations; it is therefore best to use hashed seeds.</p>\n\
<p>All methods are thread-safe, values can be requested in any order, and sequences are repeatable. </p>\n\
</div><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"func-members\"></a>\n\
Functions</h2></td></tr>\n\
<tr class=\"memitem:a8ab7fe986f687435b4d1ca6668fcda4d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">OPENMAYA_EXPORT unsigned long long&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_m_random.html#a8ab7fe986f687435b4d1ca6668fcda4d\">Rand</a> (unsigned long long i, unsigned long long seed)</td></tr>\n\
<tr class=\"memdesc:a8ab7fe986f687435b4d1ca6668fcda4d\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Generate a random number.  <a href=\"namespace_m_random.html#a8ab7fe986f687435b4d1ca6668fcda4d\">More...</a><br></td></tr>\n\
<tr class=\"separator:a8ab7fe986f687435b4d1ca6668fcda4d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a32ff9e6113bef657810cce446af19b22\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">OPENMAYA_EXPORT double&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_m_random.html#a32ff9e6113bef657810cce446af19b22\">Rand_d</a> (unsigned long long i, unsigned long long seed)</td></tr>\n\
<tr class=\"memdesc:a32ff9e6113bef657810cce446af19b22\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Generate a uniform double in [0,1).  <a href=\"namespace_m_random.html#a32ff9e6113bef657810cce446af19b22\">More...</a><br></td></tr>\n\
<tr class=\"separator:a32ff9e6113bef657810cce446af19b22\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a5bbeca7f0476b1bc786dd99fe5a69f57\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">OPENMAYA_EXPORT float&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_m_random.html#a5bbeca7f0476b1bc786dd99fe5a69f57\">Rand_f</a> (unsigned long long i, unsigned long long seed)</td></tr>\n\
<tr class=\"memdesc:a5bbeca7f0476b1bc786dd99fe5a69f57\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Generate a uniform float in [0,1).  <a href=\"namespace_m_random.html#a5bbeca7f0476b1bc786dd99fe5a69f57\">More...</a><br></td></tr>\n\
<tr class=\"separator:a5bbeca7f0476b1bc786dd99fe5a69f57\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4c4f75d1dca2bc45e15c5f30e1563101\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">OPENMAYA_EXPORT float&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_m_random.html#a4c4f75d1dca2bc45e15c5f30e1563101\">Rand_f</a> (unsigned long long i, unsigned long long seed, float rangeMin, float rangeMax)</td></tr>\n\
<tr class=\"memdesc:a4c4f75d1dca2bc45e15c5f30e1563101\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Generate a uniform float within a given range of values.  <a href=\"namespace_m_random.html#a4c4f75d1dca2bc45e15c5f30e1563101\">More...</a><br></td></tr>\n\
<tr class=\"separator:a4c4f75d1dca2bc45e15c5f30e1563101\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abcb8ec8d9d9206ba7b0f47f5f69abf2e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">OPENMAYA_EXPORT void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_m_random.html#abcb8ec8d9d9206ba7b0f47f5f69abf2e\">Rand_2f</a> (float output[2], unsigned long long i, unsigned long long seed)</td></tr>\n\
<tr class=\"memdesc:abcb8ec8d9d9206ba7b0f47f5f69abf2e\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Generate two uniform floats in [0,1).  <a href=\"namespace_m_random.html#abcb8ec8d9d9206ba7b0f47f5f69abf2e\">More...</a><br></td></tr>\n\
<tr class=\"separator:abcb8ec8d9d9206ba7b0f47f5f69abf2e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a91a097f4d949088b5176e5c01ff1f38c\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">OPENMAYA_EXPORT void&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_m_random.html#a91a097f4d949088b5176e5c01ff1f38c\">Rand_3f</a> (float output[3], unsigned long long i, unsigned long long seed)</td></tr>\n\
<tr class=\"memdesc:a91a097f4d949088b5176e5c01ff1f38c\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Generate three uniform floats in [0,1).  <a href=\"namespace_m_random.html#a91a097f4d949088b5176e5c01ff1f38c\">More...</a><br></td></tr>\n\
<tr class=\"separator:a91a097f4d949088b5176e5c01ff1f38c\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a8ab7fe986f687435b4d1ca6668fcda4d\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">unsigned long long Rand </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">unsigned long long&#160;</td>\n\
          <td class=\"paramname\"><em>i</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">unsigned long long&#160;</td>\n\
          <td class=\"paramname\"><em>seed</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Generate a random number. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">i</td><td>Requested value from the sequence of random numbers. </td></tr>\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">seed</td><td>Seed value</td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>. Random number </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a32ff9e6113bef657810cce446af19b22\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">double Rand_d </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">unsigned long long&#160;</td>\n\
          <td class=\"paramname\"><em>i</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">unsigned long long&#160;</td>\n\
          <td class=\"paramname\"><em>seed</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Generate a uniform double in [0,1). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">i</td><td>Requested value from the sequence of random numbers. </td></tr>\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">seed</td><td>Seed value</td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>. Random number </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a5bbeca7f0476b1bc786dd99fe5a69f57\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">float Rand_f </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">unsigned long long&#160;</td>\n\
          <td class=\"paramname\"><em>i</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">unsigned long long&#160;</td>\n\
          <td class=\"paramname\"><em>seed</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Generate a uniform float in [0,1). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">i</td><td>Requested value from the sequence of random numbers. </td></tr>\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">seed</td><td>Seed value</td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>. Random number </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a4c4f75d1dca2bc45e15c5f30e1563101\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">float Rand_f </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">unsigned long long&#160;</td>\n\
          <td class=\"paramname\"><em>i</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">unsigned long long&#160;</td>\n\
          <td class=\"paramname\"><em>seed</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>rangeMin</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>rangeMax</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Generate a uniform float within a given range of values. </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">i</td><td>Requested value from the sequence of random numbers. </td></tr>\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">seed</td><td>Seed value </td></tr>\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">rangeMin</td><td>Lower bound on the range of values. </td></tr>\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">rangeMax</td><td>Upper bound on the range of values.</td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>. Random number </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"abcb8ec8d9d9206ba7b0f47f5f69abf2e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">void Rand_2f </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>output</em>[2], </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">unsigned long long&#160;</td>\n\
          <td class=\"paramname\"><em>i</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">unsigned long long&#160;</td>\n\
          <td class=\"paramname\"><em>seed</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Generate two uniform floats in [0,1). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramdir\">[out]</td><td class=\"paramname\">output</td><td>Holds two random numbers from the sequence. </td></tr>\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">i</td><td>Requested value from the sequence of random numbers. </td></tr>\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">seed</td><td>Seed value </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a91a097f4d949088b5176e5c01ff1f38c\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">void Rand_3f </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>output</em>[3], </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">unsigned long long&#160;</td>\n\
          <td class=\"paramname\"><em>i</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">unsigned long long&#160;</td>\n\
          <td class=\"paramname\"><em>seed</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Generate three uniform floats in [0,1). </p>\n\
<dl class=\"params\"><dt>Parameters</dt><dd>\n\
  <table class=\"params\">\n\
    <tr><td class=\"paramdir\">[out]</td><td class=\"paramname\">output</td><td>Holds three random numbers from the sequence. </td></tr>\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">i</td><td>Requested value from the sequence of random numbers. </td></tr>\n\
    <tr><td class=\"paramdir\">[in]</td><td class=\"paramname\">seed</td><td>Seed value </td></tr>\n\
  </table>\n\
  </dd>\n\
</dl>\n\
\n\
</div>\n\
</div>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";