var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head>\n\
<link href=\"../style/prettify.css\" type=\"text/css\" rel=\"stylesheet\" />\n\
<script type=\"text/javascript\" src=\"../scripts/prettify.js\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" /><meta http-equiv=\"Content-Style-Type\" content=\"text/css\" /><meta name=\"generator\" content=\"pandoc\" /><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" /><script type=\"text/javascript\" src=\"../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>Autodesk Legal Notice</title>\n\
   </head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><style type=\"text/css\">code{white-space: pre;}</style><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/multireflink.js\"); });</script><script>$(document).ready(function () { prettyPrint(); } );</script><script></script><script></script><div id=\"reflinkdiv\"></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>Autodesk Legal Notice</h1>\n\
         </div>\n\
\n\
<div class=\'section\'><a id=\"autodesk-legal-notice\"></a></div>\n\
<p><strong>© 2018 Autodesk, Inc. All Rights Reserved.</strong> Except where otherwise noted, this work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License that can be viewed online at http://creativecommons.org/licenses/by-nc-sa/3.0/. This license content, applicable as of 16 December 2014 to this software product, is reproduced here for offline users:</p>\n\
<p>CREATIVE COMMONS CORPORATION IS NOT A LAW FIRM AND DOES NOT PROVIDE LEGAL SERVICES. DISTRIBUTION OF THIS LICENSE DOES NOT CREATE AN ATTORNEY-CLIENT RELATIONSHIP. CREATIVE COMMONS PROVIDES THIS INFORMATION ON AN &quot;AS-IS&quot; BASIS. CREATIVE COMMONS MAKES NO WARRANTIES REGARDING THE INFORMATION PROVIDED, AND DISCLAIMS LIABILITY FOR DAMAGES RESULTING FROM ITS USE.</p>\n\
<p><strong>License</strong></p>\n\
<p>THE WORK (AS DEFINED BELOW) IS PROVIDED UNDER THE TERMS OF THIS CREATIVE COMMONS PUBLIC LICENSE (&quot;CCPL&quot; OR &quot;LICENSE&quot;). THE WORK IS PROTECTED BY COPYRIGHT AND/OR OTHER APPLICABLE LAW. ANY USE OF THE WORK OTHER THAN AS AUTHORIZED UNDER THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.</p>\n\
<p>BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED HERE, YOU ACCEPT AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. TO THE EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE LICENSOR GRANTS YOU THE RIGHTS CONTAINED HERE IN CONSIDERATION OF YOUR ACCEPTANCE OF SUCH TERMS AND CONDITIONS.</p>\n\
<p><strong>1. Definitions</strong></p>\n\
<ol>\n\
<li><p><strong>&quot;Adaptation&quot;</strong> means a work based upon the Work, or upon the Work and other pre-existing works, such as a translation, adaptation, derivative work, arrangement of music or other alterations of a literary or artistic work, or phonogram or performance and includes cinematographic adaptations or any other form in which the Work may be recast, transformed, or adapted including in any form recognizably derived from the original, except that a work that constitutes a Collection will not be considered an Adaptation for the purpose of this License. For the avoidance of doubt, where the Work is a musical work, performance or phonogram, the synchronization of the Work in timed-relation with a moving image (&quot;synching&quot;) will be considered an Adaptation for the purpose of this License.</p></li>\n\
<li><p><strong>&quot;Collection&quot;</strong> means a collection of literary or artistic works, such as encyclopedias and anthologies, or performances, phonograms or broadcasts, or other works or subject matter other than works listed in Section 1(g) below, which, by reason of the selection and arrangement of their contents, constitute intellectual creations, in which the Work is included in its entirety in unmodified form along with one or more other contributions, each constituting separate and independent works in themselves, which together are assembled into a collective whole. A work that constitutes a Collection will not be considered an Adaptation (as defined above) for the purposes of this License.</p></li>\n\
<li><p><strong>&quot;Distribute&quot;</strong> means to make available to the public the original and copies of the Work or Adaptation, as appropriate, through sale or other transfer of ownership.</p></li>\n\
<li><p><strong>&quot;License Elements&quot;</strong> means the following high-level license attributes as selected by Licensor and indicated in the title of this License: Attribution, Noncommercial, ShareAlike.</p></li>\n\
<li><p><strong>&quot;Licensor&quot;</strong> means the individual, individuals, entity or entities that offer(s) the Work under the terms of this License.</p></li>\n\
<li><p><strong>&quot;Original Author&quot;</strong> means, in the case of a literary or artistic work, the individual, individuals, entity or entities who created the Work or if no individual or entity can be identified, the publisher; and in addition (i) in the case of a performance the actors, singers, musicians, dancers, and other persons who act, sing, deliver, declaim, play in, interpret or otherwise perform literary or artistic works or expressions of folklore; (ii) in the case of a phonogram the producer being the person or legal entity who first fixes the sounds of a performance or other sounds; and, (iii) in the case of broadcasts, the organization that transmits the broadcast.</p></li>\n\
<li><p><strong>&quot;Work&quot;</strong> means the literary and/or artistic work offered under the terms of this License including without limitation any production in the literary, scientific and artistic domain, whatever may be the mode or form of its expression including digital form, such as a book, pamphlet and other writing; a lecture, address, sermon or other work of the same nature; a dramatic or dramatico-musical work; a choreographic work or entertainment in dumb show; a musical composition with or without words; a cinematographic work to which are assimilated works expressed by a process analogous to cinematography; a work of drawing, painting, architecture, sculpture, engraving or lithography; a photographic work to which are assimilated works expressed by a process analogous to photography; a work of applied art; an illustration, map, plan, sketch or three-dimensional work relative to geography, topography, architecture or science; a performance; a broadcast; a phonogram; a compilation of data to the extent it is protected as a copyrightable work; or a work performed by a variety or circus performer to the extent it is not otherwise considered a literary or artistic work.</p></li>\n\
<li><p><strong>&quot;You&quot;</strong> means an individual or entity exercising rights under this License who has not previously violated the terms of this License with respect to the Work, or who has received express permission from the Licensor to exercise rights under this License despite a previous violation.</p></li>\n\
<li><p><strong>&quot;Publicly Perform&quot;</strong> means to perform public recitations of the Work and to communicate to the public those public recitations, by any means or process, including by wire or wireless means or public digital performances; to make available to the public Works in such a way that members of the public may access these Works from a place and at a place individually chosen by them; to perform the Work to the public by any means or process and the communication to the public of the performances of the Work, including by public digital performance; to broadcast and rebroadcast the Work by any means including signs, sounds or images.</p></li>\n\
<li><p><strong>&quot;Reproduce&quot;</strong> means to make copies of the Work by any means including without limitation by sound or visual recordings and the right of fixation and reproducing fixations of the Work, including storage of a protected performance or phonogram in digital form or other electronic medium.</p></li>\n\
</ol>\n\
<p><strong>2. Fair Dealing Rights.</strong> Nothing in this License is intended to reduce, limit, or restrict any uses free from copyright or rights arising from limitations or exceptions that are provided for in connection with the copyright protection under copyright law or other applicable laws.</p>\n\
<p><strong>3. License Grant.</strong> Subject to the terms and conditions of this License, Licensor hereby grants You a worldwide, royalty-free, non-exclusive, perpetual (for the duration of the applicable copyright) license to exercise the rights in the Work as stated below:</p>\n\
<ul>\n\
<li><ol>\n\
<li>to Reproduce the Work, to incorporate the Work into one or more Collections, and to Reproduce the Work as incorporated in the Collections;</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>to create and Reproduce Adaptations provided that any such Adaptation, including any translation in any medium, takes reasonable steps to clearly label, demarcate or otherwise identify that changes were made to the original Work. For example, a translation could be marked &quot;The original work was translated from English to Spanish,&quot; or a modification could indicate &quot;The original work has been modified.&quot;;</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>to Distribute and Publicly Perform the Work including as incorporated in Collections; and,</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>to Distribute and Publicly Perform Adaptations.</li>\n\
</ol></li>\n\
</ul>\n\
<p>The above rights may be exercised in all media and formats whether now known or hereafter devised. The above rights include the right to make such modifications as are technically necessary to exercise the rights in other media and formats. Subject to Section 8(f), all rights not expressly granted by Licensor are hereby reserved, including but not limited to the rights described in Section 4(e).</p>\n\
<p><strong>4. Restrictions.</strong> The license granted in Section 3 above is expressly made subject to and limited by the following restrictions:</p>\n\
<ul>\n\
<li><ol>\n\
<li>You may Distribute or Publicly Perform the Work only under the terms of this License. You must include a copy of, or the Uniform Resource Identifier (URI) for, this License with every copy of the Work You Distribute or Publicly Perform. You may not offer or impose any terms on the Work that restrict the terms of this License or the ability of the recipient of the Work to exercise the rights granted to that recipient under the terms of the License. You may not sublicense the Work. You must keep intact all notices that refer to this License and to the disclaimer of warranties with every copy of the Work You Distribute or Publicly Perform. When You Distribute or Publicly Perform the Work, You may not impose any effective technological measures on the Work that restrict the ability of a recipient of the Work from You to exercise the rights granted to that recipient under the terms of the License. This Section 4(a) applies to the Work as incorporated in a Collection, but this does not require the Collection apart from the Work itself to be made subject to the terms of this License. If You create a Collection, upon notice from any Licensor You must, to the extent practicable, remove from the Collection any credit as required by Section 4(d), as requested. If You create an Adaptation, upon notice from any Licensor You must, to the extent practicable, remove from the Adaptation any credit as required by Section 4(d), as requested.</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>You may Distribute or Publicly Perform an Adaptation only under: (i) the terms of this License; (ii) a later version of this License with the same License Elements as this License; (iii) a Creative Commons jurisdiction license (either this or a later license version) that contains the same License Elements as this License (e.g., Attribution-NonCommercial-ShareAlike 3.0 US) (&quot;Applicable License&quot;). You must include a copy of, or the URI, for Applicable License with every copy of each Adaptation You Distribute or Publicly Perform. You may not offer or impose any terms on the Adaptation that restrict the terms of the Applicable License or the ability of the recipient of the Adaptation to exercise the rights granted to that recipient under the terms of the Applicable License. You must keep intact all notices that refer to the Applicable License and to the disclaimer of warranties with every copy of the Work as included in the Adaptation You Distribute or Publicly Perform. When You Distribute or Publicly Perform the Adaptation, You may not impose any effective technological measures on the Adaptation that restrict the ability of a recipient of the Adaptation from You to exercise the rights granted to that recipient under the terms of the Applicable License. This Section 4(b) applies to the Adaptation as incorporated in a Collection, but this does not require the Collection apart from the Adaptation itself to be made subject to the terms of the Applicable License.</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>You may not exercise any of the rights granted to You in Section 3 above in any manner that is primarily intended for or directed toward commercial advantage or private monetary compensation. The exchange of the Work for other copyrighted works by means of digital file-sharing or otherwise shall not be considered to be intended for or directed toward commercial advantage or private monetary compensation, provided there is no payment of any monetary compensation in connection with the exchange of copyrighted works.</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>If You Distribute, or Publicly Perform the Work or any Adaptations or Collections, You must, unless a request has been made pursuant to Section 4(a), keep intact all copyright notices for the Work and provide, reasonable to the medium or means You are utilizing: (i) the name of the Original Author (or pseudonym, if applicable) if supplied, and/or if the Original Author and/or Licensor designate another party or parties (e.g., a sponsor institute, publishing entity, journal) for attribution (&quot;Attribution Parties&quot;) in Licensor&#39;s copyright notice, terms of service or by other reasonable means, the name of such party or parties; (ii) the title of the Work if supplied; (iii) to the extent reasonably practicable, the URI, if any, that Licensor specifies to be associated with the Work, unless such URI does not refer to the copyright notice or licensing information for the Work; and, (iv) consistent with Section 3(b), in the case of an Adaptation, a credit identifying the use of the Work in the Adaptation (e.g., &quot;French translation of the Work by Original Author,&quot; or &quot;Screenplay based on original Work by Original Author&quot;). The credit required by this Section 4(d) may be implemented in any reasonable manner; provided, however, that in the case of a Adaptation or Collection, at a minimum such credit will appear, if a credit for all contributing authors of the Adaptation or Collection appears, then as part of these credits and in a manner at least as prominent as the credits for the other contributing authors. For the avoidance of doubt, You may only use the credit required by this Section for the purpose of attribution in the manner set out above and, by exercising Your rights under this License, You may not implicitly or explicitly assert or imply any connection with, sponsorship or endorsement by the Original Author, Licensor and/or Attribution Parties, as appropriate, of You or Your use of the Work, without the separate, express prior written permission of the Original Author, Licensor and/or Attribution Parties.</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>For the avoidance of doubt:</li>\n\
</ol>\n\
<ul>\n\
<li><ol>\n\
<li>Non-waivable Compulsory License Schemes. In those jurisdictions in which the right to collect royalties through any statutory or compulsory licensing scheme cannot be waived, the Licensor reserves the exclusive right to collect such royalties for any exercise by You of the rights granted under this License;</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>Waivable Compulsory License Schemes. In those jurisdictions in which the right to collect royalties through any statutory or compulsory licensing scheme can be waived, the Licensor reserves the exclusive right to collect such royalties for any exercise by You of the rights granted under this License if Your exercise of such rights is for a purpose or use which is otherwise than noncommercial as permitted under Section 4(c) and otherwise waives the right to collect royalties through any statutory or compulsory licensing scheme; and,</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>Voluntary License Schemes. The Licensor reserves the right to collect royalties, whether individually or, in the event that the Licensor is a member of a collecting society that administers voluntary licensing schemes, via that society, from any exercise by You of the rights granted under this License that is for a purpose or use which is otherwise than noncommercial as permitted under Section 4(c).</li>\n\
</ol></li>\n\
</ul></li>\n\
<li><ol>\n\
<li>Except as otherwise agreed in writing by the Licensor or as may be otherwise permitted by applicable law, if You Reproduce, Distribute or Publicly Perform the Work either by itself or as part of any Adaptations or Collections, You must not distort, mutilate, modify or take other derogatory action in relation to the Work which would be prejudicial to the Original Author&#39;s honor or reputation. Licensor agrees that in those jurisdictions (e.g. Japan), in which any exercise of the right granted in Section 3(b) of this License (the right to make Adaptations) would be deemed to be a distortion, mutilation, modification or other derogatory action prejudicial to the Original Author&#39;s honor and reputation, the Licensor will waive or not assert, as appropriate, this Section, to the fullest extent permitted by the applicable national law, to enable You to reasonably exercise Your right under Section 3(b) of this License (right to make Adaptations) but not otherwise.</li>\n\
</ol></li>\n\
</ul>\n\
<p><strong>5. Representations, Warranties and Disclaimer</strong></p>\n\
<p>UNLESS OTHERWISE MUTUALLY AGREED TO BY THE PARTIES IN WRITING AND TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, LICENSOR OFFERS THE WORK AS-IS AND MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND CONCERNING THE WORK, EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT, OR THE ABSENCE OF LATENT OR OTHER DEFECTS, ACCURACY, OR THE PRESENCE OF ABSENCE OF ERRORS, WHETHER OR NOT DISCOVERABLE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THIS EXCLUSION MAY NOT APPLY TO YOU.</p>\n\
<p><strong>6. Limitation on Liability.</strong> EXCEPT TO THE EXTENT REQUIRED BY APPLICABLE LAW, IN NO EVENT WILL LICENSOR BE LIABLE TO YOU ON ANY LEGAL THEORY FOR ANY SPECIAL, INCIDENTAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES ARISING OUT OF THIS LICENSE OR THE USE OF THE WORK, EVEN IF LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>\n\
<p><strong>7. Termination</strong></p>\n\
<ul>\n\
<li><ol>\n\
<li>This License and the rights granted hereunder will terminate automatically upon any breach by You of the terms of this License. Individuals or entities who have received Adaptations or Collections from You under this License, however, will not have their licenses terminated provided such individuals or entities remain in full compliance with those licenses. Sections 1, 2, 5, 6, 7, and 8 will survive any termination of this License.</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>Subject to the above terms and conditions, the license granted here is perpetual (for the duration of the applicable copyright in the Work). Notwithstanding the above, Licensor reserves the right to release the Work under different license terms or to stop distributing the Work at any time; provided, however that any such election will not serve to withdraw this License (or any other license that has been, or is required to be, granted under the terms of this License), and this License will continue in full force and effect unless terminated as stated above.</li>\n\
</ol></li>\n\
</ul>\n\
<p><strong>8. Miscellaneous</strong></p>\n\
<ul>\n\
<li><ol>\n\
<li>Each time You Distribute or Publicly Perform the Work or a Collection, the Licensor offers to the recipient a license to the Work on the same terms and conditions as the license granted to You under this License.</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>Each time You Distribute or Publicly Perform an Adaptation, Licensor offers to the recipient a license to the original Work on the same terms and conditions as the license granted to You under this License.</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>If any provision of this License is invalid or unenforceable under applicable law, it shall not affect the validity or enforceability of the remainder of the terms of this License, and without further action by the parties to this agreement, such provision shall be reformed to the minimum extent necessary to make such provision valid and enforceable.</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>No term or provision of this License shall be deemed waived and no breach consented to unless such waiver or consent shall be in writing and signed by the party to be charged with such waiver or consent.</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>This License constitutes the entire agreement between the parties with respect to the Work licensed here. There are no understandings, agreements or representations with respect to the Work not specified here. Licensor shall not be bound by any additional provisions that may appear in any communication from You. This License may not be modified without the mutual written agreement of the Licensor and You.</li>\n\
</ol></li>\n\
<li><ol>\n\
<li>The rights granted under, and the subject matter referenced, in this License were drafted utilizing the terminology of the Berne Convention for the Protection of Literary and Artistic Works (as amended on September 28, 1979), the Rome Convention of 1961, the WIPO Copyright Treaty of 1996, the WIPO Performances and Phonograms Treaty of 1996 and the Universal Copyright Convention (as revised on July 24, 1971). These rights and subject matter take effect in the relevant jurisdiction in which the License terms are sought to be enforced according to the corresponding provisions of the implementation of those treaty provisions in the applicable national law. If the standard suite of rights granted under applicable copyright law includes additional rights not granted under this License, such additional rights are deemed to be included in the License; this License is not intended to restrict the license of any rights under applicable law.</li>\n\
</ol></li>\n\
</ul>\n\
<p><strong>Creative Commons Notice</strong></p>\n\
<p>Creative Commons is not a party to this License, and makes no warranty whatsoever in connection with the Work. Creative Commons will not be liable to You or any party on any legal theory for any damages whatsoever, including without limitation any general, special, incidental or consequential damages arising in connection to this license. Notwithstanding the foregoing two (2) sentences, if Creative Commons has expressly identified itself as the Licensor hereunder, it shall have all rights and obligations of Licensor.</p>\n\
<p>Except for the limited purpose of indicating to the public that the Work is licensed under the CCPL, Creative Commons does not authorize the use by either party of the trademark &quot;Creative Commons&quot; or any related trademark or logo of Creative Commons without the prior written consent of Creative Commons. Any permitted use will be in compliance with Creative Commons&#39; then-current trademark usage guidelines, as may be published on its website or otherwise made available upon request from time to time. For the avoidance of doubt, this trademark restriction does not form part of this License.</p>\n\
<p>Creative Commons may be contacted at <a href=\'HTTPS://CREATIVECOMMONS.ORG/\' title=\'\'>https://creativecommons.org/</a>.</p>\n\
<p>Certain materials included in this publication are reprinted with the permission of the copyright holder.</p>\n\
<div class=\'section\'><a id=\"creative-commons-faq\"></a><h2 id=\"creative-commons-faq\">Creative Commons FAQ</h2></div>\n\
<p>Autodesk&#39;s Creative Commons FAQ can be viewed online at https://knowledge.autodesk.com/customer-service/share-the-knowledge, and is reproduced here for offline users.</p>\n\
<p>Creative Commons is a simple, open licensing model which allows individuals to freely modify, remix, and share digital content created for learning and support.</p>\n\
<p>Borrow from the Autodesk Learning, Support and Video libraries to build a new learning experience for anyone with any particular need or interest. It&#39;s out there. You can use it. It&#39;s yours.</p>\n\
<p>In collaboration with Creative Commons, Autodesk invites you to share your knowledge with the rest of the world, inspiring others to learn, achieve goals, and ignite creativity.</p>\n\
<p><strong>What is Creative Commons?</strong></p>\n\
<p>Creative Commons (CC) is a nonprofit organization that offers a simple licensing model that frees digital content to enable anyone to modify, remix, and share creative works.</p>\n\
<p><strong>How do I know if Autodesk learning content and Autodesk University content is available under Creative Commons?</strong></p>\n\
<p>All Autodesk learning content and Autodesk University content released under Creative Commons is explicitly marked with a Creative Commons icon specifying what you can and cannot do. Always follow the terms of the stated license.</p>\n\
<p><strong>What Autodesk learning content is currently available under Creative Commons?</strong></p>\n\
<p>Over time, Autodesk will release more and more learning content under the Creative Commons licenses.</p>\n\
<p>Currently available learning content:</p>\n\
<ul>\n\
<li>Autodesk online help-Online help for many Autodesk products, including its embedded media such as images and help movies.</li>\n\
<li>Autodesk Learning Videos-A range of video-based learning content, including the video tutorials on the Autodesk YouTube™ Learning Channels and their associated iTunes® podcasts.</li>\n\
<li>Autodesk downloadable materials-Downloadable 3D assets, digital footage, and other files you can use to follow along on your own time.</li>\n\
</ul>\n\
<p><strong>Is Autodesk learning and support content copyrighted?</strong></p>\n\
<p>Yes. Creative Commons licensing does not replace copyright. Copyright remains with Autodesk or its suppliers, as applicable. But it makes the terms of use much more flexible.</p>\n\
<p><strong>What do the Autodesk Creative Commons licenses allow?</strong></p>\n\
<p>Autodesk makes some of its learning and support content available under two distinct Creative Commons licenses. The learning content is clearly marked with the applicable Creative Commons license. You must comply with the following conditions:</p>\n\
<ul>\n\
<li><strong>Attribution-NonCommercial-ShareAlike (CC BY-NC-SA)</strong> This license lets you copy, distribute, display, remix, tweak, and build upon our work noncommercially, as long as you credit Autodesk and license your new creations under the identical terms. Terms of this license can be viewed online at https://creativecommons.org/licenses/by-nc-sa/3.0/us/</li>\n\
<li><strong>Attribution-NonCommercial-No Derivative Works (CC BY-NC-ND)</strong> This license lets you copy, distribute, and display only verbatim copies of our work as long as you credit us, but you cannot alter the learning content in any way or use it commercially. Terms of this license can be viewed online at https://creativecommons.org/licenses/by-nc-nd/3.0/us/deed.en_US</li>\n\
<li><strong>Special permissions on content marked as No Derivative Works</strong> For video-based learning content marked as No Derivative Works (ND), Autodesk grants you special permission to make modifications but only for the purpose of translating the video content into another language.</li>\n\
</ul>\n\
<p>These conditions can be modified only by explicit permission of Autodesk, Inc. Send requests for modifications outside of these license terms to <a href=\'#!/url=./dev_help/MAILTO:CREATIVECOMMONS@AUTODESK.COM\' title=\'\'>creativecommons@autodesk.com</a>.</p>\n\
<p><strong>Can I get special permission to do something different with the learning content?</strong></p>\n\
<p>Unless otherwise stated, our Creative Commons conditions can be modified only by explicit permission of Autodesk, Inc. If you have any questions or requests for modifications outside of these license terms, email us at <a href=\'#!/url=./dev_help/MAILTO:CREATIVECOMMONS@AUTODESK.COM\' title=\'\'>creativecommons@autodesk.com</a>.</p>\n\
<p><strong>How do I attribute Autodesk learning content?</strong></p>\n\
<p>You must explicitly credit Autodesk, Inc., as the original source of the materials. This is a standard requirement of the Attribution (BY) term in all Creative Commons licenses. In some cases, such as for the Autodesk video learning content, we specify exactly how we would like to be attributed.</p>\n\
<p>This is usually described on the video&#39;s end-plate. For the most part providing the title of the work, the URL where the work is hosted, and a credit to Autodesk, Inc., is quite acceptable. Also, remember to keep intact any copyright notice associated with the work. This may sound like a lot of information, but there is flexibility in the way you present it.</p>\n\
<p>Here are some examples:</p>\n\
<p>&quot;This document contains content adapted from the Autodesk® Maya® Help, available under a Creative Commons Attribution-NonCommercial-Share Alike license. Copyright © Autodesk, Inc.&quot;</p>\n\
<p>&quot;This is a Finnish translation of a video created by the Autodesk Maya Learning Channel @ <a href=\'HTTP://WWW.YOUTUBE.COM/MAYAHOWTOS\' title=\'\'>www.youtube.com/mayahowtos</a>. Copyright © Autodesk, Inc.&quot;</p>\n\
<p>&quot;Special thanks to the Autodesk® 3ds Max® Learning Channel @ <a href=\'HTTP://WWW.YOUTUBE.COM/3DSMAXHOWTOS\' title=\'\'>www.youtube.com/3dsmaxhowtos</a>. Copyright © Autodesk, Inc.&quot;</p>\n\
<p><strong>Do I follow YouTube&#39;s standard license or Autodesk&#39;s Creative Commons license?</strong></p>\n\
<p>The videos of the Autodesk Learning Channels on YouTube are uploaded under YouTube&#39;s standard license policy. Nonetheless, these videos are released by Autodesk as Creative Commons Attribution-NonCommercial-No Derivative Works (CC BY-NC-ND) and are marked as such.</p>\n\
<p>You are free to use our video learning content according to the Creative Commons license under which they are released.</p>\n\
<p><strong>Where can I easily download Autodesk learning videos?</strong></p>\n\
<p>Most of the Autodesk Learning Channels have an associated iTunes podcast from where you can download the same videos and watch them offline. When translating Autodesk learning videos, we recommend downloading the videos from the iTunes podcasts.</p>\n\
<p><strong>Can I translate Autodesk learning videos?</strong></p>\n\
<p>Yes. Even though our learning videos are licensed as No Derivative Works (ND), we grant everyone permission to translate the audio and subtitles into other languages. In fact, if you want to recapture the video tutorial as-is but show the user interface in another language, you are free to do so. Be sure to give proper attribution as indicated on the video&#39;s Creative Commons end-plate. This special permission only applies to translation projects. Requests for modifications outside of these license terms can be directed to <em>creativecommons@autodesk.com</em>.</p>\n\
<p><strong>How do I let others know that I have translated Autodesk learning content into another language?</strong></p>\n\
<p>Autodesk is happy to see its learning content translated into as many different languages as possible. If you translate our videos or any of our learning content into other languages, let us know. We can help promote your contributions to our growing multilingual community. In fact, we encourage you to find creative ways to share our learning content with your friends, family, students, colleagues, and communities around the world. Contact us at <em>creativecommons@autodesk.com</em>.</p>\n\
<p><strong>I have translated Autodesk learning videos into other languages. Can I upload them to my own YouTube channel?</strong></p>\n\
<p>Yes, please do and let us know where to find them so that we can help promote your contributions to our growing multilingual Autodesk community. Contact us at <em>creativecommons@autodesk.com</em>.</p>\n\
<p><strong>Can I repost or republish Autodesk learning content on my site or blog?</strong></p>\n\
<p>Yes, you can make Autodesk learning material available on your site or blog as long as you follow the terms of the Creative Commons license under which the learning content is released. If you are simply referencing the learning content as-is, then we recommend that you link to it or embed it from where it is hosted by Autodesk. That way the content will always be fresh. If you have translated or remixed our learning content, then by all means you can host it yourself. Let us know about it, and we can help promote your contributions to our global learning community. Contact us at <em>creativecommons@autodesk.com</em>.</p>\n\
<p><strong>Can I show Autodesk learning content during my conference?</strong></p>\n\
<p>Yes, as long as it&#39;s within the scope of a noncommercial event, and as long as you comply with the terms of the Creative Commons license outlined above. In particular, the videos must be shown unedited with the exception of modifications for the purpose of translation. If you wish to use Autodesk learning content in a commercial context, contact us with a request for permission at <em>creativecommons@autodesk.com</em>.</p>\n\
<p><strong>Can I use Autodesk learning content in my classroom?</strong></p>\n\
<p>Yes, as long as you comply with the terms of the Creative Commons license under which the learning material is released. Many teachers use Autodesk learning content to stimulate discussions with students or to complement course materials, and we encourage you to do so as well.</p>\n\
<p><strong>Can I re-edit and remix Autodesk video learning content?</strong></p>\n\
<p>No, but for one exception. Our Creative Commons BY-NC-ND license clearly states that &quot;derivative works&quot; of any kind (edits, cuts, remixes, mashups, and so on) are not allowed without explicit permission from Autodesk. This is essential for preserving the integrity of our instructors&#39; ideas. However, we do give you permission to modify our videos for the purpose of translating them into other languages.</p>\n\
<p><strong>Can I re-edit and remix Autodesk downloadable 3D assets and footage?</strong></p>\n\
<p>Yes. The Autodesk Learning Channels on YouTube provide downloadable 3D assets, footage, and other files for you to follow along with the video tutorials on your own time. This downloadable material is made available under a Creative Commons Attribution-NonCommercial-ShareAlike (CC BY-NC-SA) license. You can download these materials and experiment with them, but your remixes must give us credit as the original source of the content and be shared under the identical license terms.</p>\n\
<p><strong>Can I use content from Autodesk online help to create new materials for a specific audience?</strong></p>\n\
<p>Yes, if you want to help a specific audience learn how to optimize the use of their Autodesk software, there is no need to start from scratch. You can use, remix, or enrich the relevant help content and include it in your book, instructions, examples, or workflows you create, then Share-Alike with the community. Always be sure to comply with the terms of the Creative Commons license under which the learning content is released.</p>\n\
<p><strong>What are the best practices for marking content with Creative Commons Licenses?</strong></p>\n\
<p>When reusing a CC-licensed work (by sharing the original or a derivative based on the original), it is important to keep intact any copyright notice associated with the work, including the Creative Commons license being used. Make sure you abide by the license conditions provided by the licensor, in this case Autodesk, Inc.</p>\n\
<p><strong>Trademarks</strong></p>\n\
<p>The following are registered trademarks or trademarks of Autodesk, Inc., and/or its subsidiaries and/or affiliates in the USA and other countries: 123D, 3ds Max, ADSK, Alias, ArtCAM, ATC, AutoCAD LT, AutoCAD, Autodesk, the Autodesk logo, Autodesk 123D, Autodesk Alias, Autodesk Forge, Autodesk Fusion, Autodesk Inventor, AutoSnap, BIM 360, Buzzsaw, CADmep, CAMduct, Civil 3D, Configurator 360, Dancing Baby (image), DWF, DWG, DWG (design/logo), DWG Extreme, DWG TrueConvert, DWG TrueView, DWGX, DXF, Eagle, Ember, ESTmep, FBX, FeatureCAM, Flame, FormIt 360, Fusion 360, Fusion Lifecycle, The Future of Making Things, Glue, Green Building Studio, InfraWorks, Instructables, Instructables (stylized robot design/logo), Inventor, Inventor HSM, Inventor LT, Make Anything, Maya, Maya LT, Moldflow, MotionBuilder, Mudbox, Navisworks, Opticore, P9, Pier 9, PowerInspect, PowerMill, PowerShape, Publisher 360, RasterDWG, RealDWG, ReCap, ReCap 360, Remake, Revit LT, Revit, Scaleform, Shotgun, Showcase, Showcase 360, SketchBook, Softimage, Tinkercad, Tinkerplay, TrustedDWG, VRED.</p>\n\
<p>All other brand names, product names or trademarks belong to their respective holders.</p>\n\
<p><strong>Disclaimer</strong></p>\n\
<p>THIS PUBLICATION AND THE INFORMATION CONTAINED HEREIN IS MADE AVAILABLE BY AUTODESK, INC. &quot;AS IS.&quot; AUTODESK, INC. DISCLAIMS ALL WARRANTIES, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE REGARDING THESE MATERIALS.</p>\n\
      <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";