var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head>\n\
<link href=\"../../style/prettify.css\" type=\"text/css\" rel=\"stylesheet\">\n\
<script type=\"text/javascript\" src=\"../../scripts/prettify.js\"></script><script src=\"../../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><meta http-equiv=\"Content-Style-Type\" content=\"text/css\"><meta name=\"generator\" content=\"pandoc\"><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>Autodesk Maya 2013</title>\n\
   <meta name=\"topic-subtype\" content=\"C++\"></head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><style type=\"text/css\">code{white-space: pre;}</style><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/multireflink.js\"); });</script><script>$(document).ready(function () { prettyPrint(); } );</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script></script><script></script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div><div id=\"reflinkdiv\"></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>Autodesk Maya 2013</h1>\n\
         </div>\n\
\n\
<div class=\'section\'><a id=\"autodesk-maya-2013\"></a></div>\n\
<div class=\'section\'><a id=\"whats-new\"></a><h2 id=\"whats-new\">What&#39;s New?</h2></div>\n\
<div class=\'section\'><a id=\"device-data-streaming\"></a><h3 id=\"device-data-streaming\">Device Data Streaming</h3></div>\n\
<p>The <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MPxThreadedDeviceNode\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_px_threaded_device_node.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MPxThreadedDeviceNode</a></span> and <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MPxClientDeviceNode\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_px_client_device_node.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MPxClientDeviceNode</a></span> proxy classes have been added to let you stream data from external sources into the Dependency Graph via custom plug-in nodes. The following new <span class=\'code\'>Maya2013/devkit/plug-ins/</span> examples demonstrate how to use these classes:</p>\n\
<ul>\n\
<li><span class=\'code\'>gameInputDevice</span> (Windows)</li>\n\
<li><span class=\'code\'>udpDevice</span> (Linux)</li>\n\
<li><span class=\'code\'>randomizerDevice</span> (All platforms)</li>\n\
</ul>\n\
<div class=\'section\'><a id=\"ui-drag-and-drop\"></a><h3 id=\"ui-drag-and-drop\">UI Drag and Drop</h3></div>\n\
<p>New classes have been added to provide callback hooks into Maya&#39;s drag-and-drop mechanism:</p>\n\
<ul>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MExternalDropCallback\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_external_drop_callback.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MExternalDropCallback</a></span> - This class will be used to register callbacks to gain access to Maya&#39;s drag-and-drop information when dropping external objects into Maya. You can replace or augment this drop behavior for external drag-and-drop operations.</li>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MExternalDropData\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_external_drop_data.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MExternalDropData</a></span> - This class represents the data carried within a drag-and-drop operation when dragging from an external application. This class is used by <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MExternalDropCallback\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_external_drop_callback.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MExternalDropCallback</a></span>.</li>\n\
</ul>\n\
<div class=\'section\'><a id=\"viewport-2.0\"></a><h3 id=\"viewport-2.0\">Viewport 2.0</h3></div>\n\
<p>A group of new classes has been added under the <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MHWRender\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/namespace_m_h_w_render.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MHWRender</a></span> namespace to work with index buffers and vertex buffers in Viewport 2.0</p>\n\
<ul>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MComponentDataIndexing\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_component_data_indexing.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_render_1_1_m_component_data_indexing.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MComponentDataIndexing</a></span> - Stores index mapping when vertices are shared.</li>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MComponentDataIndexingList\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_component_data_indexing_list.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_render_1_1_m_component_data_indexing_list.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MComponentDataIndexingList</a></span> - A list containing <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MComponentDataIndexing\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_component_data_indexing.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_render_1_1_m_component_data_indexing.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MComponentDataIndexing</a></span> objects.</li>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MGeometryUtilities\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_geometry_utilities.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_render_1_1_m_geometry_utilities.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MGeometryUtilities</a></span> - Utility class for rendering geometry in Viewport 2.0. The <span class=\'code\'>wireframeColor()</span> function gets the final wireframe color.</li>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MGeometryExtractor\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_geometry_extractor.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_render_1_1_m_geometry_extractor.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MGeometryExtractor</a></span> - Base class for extracting renderable geometry. Create an instance of this class to populate buffers with vertex and indexing data.</li>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MIndexBufferDescriptor\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_index_buffer_descriptor.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_render_1_1_m_index_buffer_descriptor.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MIndexBufferDescriptor</a></span> - Represents a description of an indexing scheme, indexing type, primitive type, primitive stride, and component information.</li>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MIndexBufferDescriptorList\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_index_buffer_descriptor_list.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_render_1_1_m_index_buffer_descriptor_list.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MIndexBufferDescriptorList</a></span> - A list containing <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MIndexBufferDescriptor\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_index_buffer_descriptor.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_render_1_1_m_index_buffer_descriptor.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MIndexBufferDescriptor</a></span> objects.</li>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MLightParameterInformation\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_light_parameter_information.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_render_1_1_m_light_parameter_information.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MLightParameterInformation</a></span> - Provides per-light information, accessible via <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MDrawContext\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_draw_context.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_render_1_1_m_draw_context.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MDrawContext</a></span>.</li>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MPxVertexBufferGenerator\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_px_vertex_buffer_generator.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_render_1_1_m_px_vertex_buffer_generator.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MPxVertexBufferGenerator</a></span> - Base class for user-defined vertex buffer generators.</li>\n\
</ul>\n\
<div class=\'section\'><a id=\"attribute-patterns\"></a><h3 id=\"attribute-patterns\">Attribute Patterns</h3></div>\n\
<p>New attribute pattern API classes have been added:</p>\n\
<ul>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MAttributePattern\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_attribute_pattern.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_1_1_m_attribute_pattern.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MAttributePattern</a></span> - Provides a pattern of attributes to be applied to nodes as dynamic attributes or to node classes as extension attributes.</li>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MAttributePatternArray\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_attribute_pattern_array.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MAttributePatternArray</a></span> - Provides methods for manipulating arrays of attribute patterns.</li>\n\
<li><span class=\'code\'>MPxAttributeFactory</span> - Base class for user-defined attribute pattern factories.</li>\n\
</ul>\n\
<div class=\'section\'><a id=\"module-support-for-plug-ins\"></a><h3 id=\"module-support-for-plug-ins\">Module support for plug-ins</h3></div>\n\
<p>You can now easily create a distributable deployment of your plug-in. The site administrator can setup a plug-in as a folder on a network, along with a module description file. Each user&#39;s machine should point to the module description file through the MAYA_MODULE_PATH environment variable. This way, making changes to the plug-in is simple even across multiple Maya versions and platforms.</p>\n\
<p>Multiple versions of a plug-in are now supported, where the version used is determined by a combination of the current operating system, the version of Maya, and the language setting (locale). The details of the new module file syntax are outlined in the following section.</p>\n\
<p>For more information, see:</p>\n\
<ul>\n\
<li><a href=\'#!/url=./developer/Distributing-Maya-Plug-ins/Maya-module-paths-folders-and.html\' title=\'\'>Maya module paths, folders and versions</a></li>\n\
<li><a href=\'#!/url=./developer/Distributing-Maya-Plug-ins/Recommended-workflow-for.html\' title=\'\'>Recommended workflow for plug-in modules</a></li>\n\
</ul>\n\
<p>Note: The &quot;<span class=\'code\'>devkit/plug-ins</span>&quot; folder has been reorganized so that the plug-in associated files are encapsulated under one folder and the plug-in project will be parented under a single parent solution file called &quot;<span class=\'code\'>Plug-ins.sln</span>&quot;</p>\n\
<div class=\'section\'><a id=\"whats-changed\"></a><h2 id=\"whats-changed\">What&#39;s Changed?</h2></div>\n\
<div class=\'section\'><a id=\"imageplane-node-changes\"></a><h3 id=\"imageplane-node-changes\">imagePlane node changes</h3></div>\n\
<p>The imagePlane node, which was previously a dependency node, is now a shape node (in other words, a DAG node). This may require changes to your scripts and plug-ins.</p>\n\
<p>If you have been using <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MFnDependencyNode\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_fn_dependency_node.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_1_1_m_fn_dependency_node.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MFnDependencyNode</a></span> to create imagePlane nodes, you must change your code to use <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MFnDagNode\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_fn_dag_node.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_1_1_m_fn_dag_node.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MFnDagNode</a></span> instead. Similarly, if you were using <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MDGModifier\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_d_g_modifier.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_1_1_m_d_g_modifier.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MDGModifier</a></span> to create or delete imagePlane nodes, then you must use <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MDagModifier\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_dag_modifier.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_1_1_m_dag_modifier.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MDagModifier</a></span> instead.</p>\n\
<p>Scripts and plug-ins which delete imagePlane nodes may now have to do additional work to clean up the parent transforms.</p>\n\
<p>In addition, to avoid conflicts with some of the standard DAG node attributes, the following imagePlane attributes have been renamed:</p>\n\
<table cellpadding=\"0\" cellspacing=\"0\" class=\"not-ruled\"><colgroup><col> <col> </colgroup><tbody><tr class=\"not-ruled-odd-row\"><td class=\"table-body\"><em class=\"strong\">previous name</em></td><td class=\"table-body\"><em class=\"strong\">new name</em></td></tr><tr class=\"not-ruled-even-row\"><td class=\"table-body\">center (c)</td><td class=\"table-body\">imageCenter (ic)</td></tr><tr class=\"not-ruled-odd-row\"><td class=\"table-body\">centerX (cx)</td><td class=\"table-body\">imageCenterX (icx)</td></tr><tr class=\"not-ruled-even-row\"><td class=\"table-body\">centerY (cy)</td><td class=\"table-body\">imageCenterY (icy)</td></tr><tr class=\"not-ruled-odd-row\"><td class=\"table-body\">centerZ (cz)</td><td class=\"table-body\">imageCenterZ (icz)</td></tr></tbody></table>\n\
<p>Scripts and plug-ins that refer to the child attributes by their previous names no longer work.</p>\n\
<p>Scripts and plug-ins that refer to the parent attribute by its previous name (center) appear to work but now return the center of the node&#39;s bounding box, and not the center of the image plane, which may be different.</p>\n\
      <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";