var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head>\n\
<link href=\"../../style/prettify.css\" type=\"text/css\" rel=\"stylesheet\">\n\
<script type=\"text/javascript\" src=\"../../scripts/prettify.js\"></script><script src=\"../../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><meta http-equiv=\"Content-Style-Type\" content=\"text/css\"><meta name=\"generator\" content=\"pandoc\"><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><script type=\"text/javascript\" src=\"../../scripts/utils/adsk.redirect.js\"></script>\n\
      <title>What&#39;s New in API in Maya 2017 Update 2</title>\n\
   <meta name=\"contextid\" content=\"WHATS_NEW_API_2017UPDATE2\"><meta name=\"topic-subtype\" content=\"C++\"></head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><style type=\"text/css\">code{white-space: pre;}</style><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/multireflink.js\"); });</script><script>$(document).ready(function () { prettyPrint(); } );</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script></script><script></script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div><div id=\"reflinkdiv\"></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>What&#39;s New in API in Maya 2017 Update 2</h1>\n\
         </div>\n\
\n\
<div class=\'section\'><a id=\"whats-new-in-api-in-maya-2017-update-2\"></a></div>\n\
<div class=\'section\'><a id=\"rendering\"></a><h2 id=\"rendering\">Rendering</h2></div>\n\
<div class=\'section\'><a id=\"lighting\"></a><h3 id=\"lighting\">Lighting</h3></div>\n\
<p>If a plug-in light uses the <a href=\'#!/url=./developer/Viewport-2-0-API/Maya-Viewport-2-0-API-Guide/Plug-in-Entry-Points/Registration.htmlLI_A5C606D06EA942699A9A50A68A401BF9\' title=\'\'>Light classification</a>, and the plug-in light has an <strong>Exposure</strong> attribute, this attribute is now respected. The <strong>Exposure</strong> attribute has been added to all light types in the <em>apiDirectionalLightShape</em> devkit example for demonstration.</p>\n\
<p>You can now use the <span class=\'code\'>/drawdb/light/image</span> classification to register a plug-in node so that it behaves like an internal IBL (image) light. A application is the aiSkyDomeLight. See <a href=\'#!/url=./developer/Viewport-2-0-API/Maya-Viewport-2-0-API-Guide/Advanced-Topics/Image-based-lighting.html\' title=\'\'>Image based lighting</a>.</p>\n\
<p>After registering with this classification, you can then control these lighting attributes: color, envRotationY, sampling, intensity, and exposure.</p>\n\
<p>The <strong>Color</strong> attribute is mandatory and must be defined; otherwise, your node will appear black.</p>\n\
<p>As an example, the <em>apiDirectionalLightShape</em> plug-in in the devkit now includes an apiImageLightShape image light.</p>\n\
<div class=\'section\'><a id=\"shading\"></a><h3 id=\"shading\">Shading</h3></div>\n\
<p>Added the <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MShaderInstance::writeEffectSourceToFile()\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_shader_instance.html#afcbf6a45dfeef2b89b6017448c1309ac&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MShaderInstance::writeEffectSourceToFile()</a></span> method for debugging custom shader fragment development. Use this method to write the final effect source to a file so you can perform validation on custom shader fragments on all device APIs. To validate your shader plug-in, you can bind a temporary draw context with a shader instance generated from the effect source file.</p>\n\
<div class=\'section\'><a id=\"compiler-requirements-for-the-mac-os-x-environment\"></a><h2 id=\"compiler-requirements-for-the-mac-os-x-environment\">Compiler requirements for the Mac OS X environment</h2></div>\n\
<p>To compile plug-ins and standalone applications on Mac OS X, you must now have the following installed: Mavericks 10.9.5, Xcode 6.1.1 with SDK 10.9, clang with libc++. For more information see <a href=\'#!/url=./developer/Setting-up-your-build/Mac-OS-X-environment.html\' title=\'\'>Mac OS X environment</a>.</p>\n\
<div class=\'section\'><a id=\"plug-in-example-updates\"></a><h2 id=\"plug-in-example-updates\">Plug-in example updates</h2></div>\n\
<ul>\n\
<li>A new <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"workspaceControlCmd.cpp\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/workspace_control_cmd_8cpp-example.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">workspaceControlCmd.cpp</a></span> plug-in example demonstrates a way to create customized Maya UI that is compatible with Maya Workspaces.</li>\n\
<li>The <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"footPrintNode/footPrintNode.cpp\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/foot_print_node_2foot_print_node_8cpp-example.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">footPrintNode/footPrintNode.cpp</a></span> and <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"footPrintNode_GeometryOverride/footPrintNode_GeometryOverride.cpp\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/foot_print_node__geometry_override_2foot_print_node__geometry_override_8cpp-example.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">footPrintNode_GeometryOverride/footPrintNode_GeometryOverride.cpp</a></span> examples have been improved to provide better performance in Viewport 2.0 by merging geometry and render items at the plug-in level.</li>\n\
<li><p>The <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"apiMeshShape/apiMeshSubSceneOverride.cpp\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/api_mesh_shape_2api_mesh_sub_scene_override_8cpp-example.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">apiMeshShape/apiMeshSubSceneOverride.cpp</a></span> example has been updated to include the following <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MHWRender::MPxSubSceneOverride\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_px_sub_scene_override.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MHWRender::MPxSubSceneOverride</a></span> class virtual functions:</p>\n\
<ul>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MPxSubSceneOverride::getSelectionPath()\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_px_sub_scene_override.html#af3b88498daedce6cd2e55103c58160a4&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MPxSubSceneOverride::getSelectionPath()</a></span></li>\n\
<li><span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MPxSubSceneOverride::getInstancedSelectionPath()\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_px_sub_scene_override.html#a3d9b68da81d724902522fe2bf5f809c5&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MPxSubSceneOverride::getInstancedSelectionPath()</a></span></li>\n\
</ul>\n\
<p>Implementing these functions allows <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MPxSubSceneOverride\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_px_sub_scene_override.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_render_1_1_m_px_sub_scene_override.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MPxSubSceneOverride</a></span> plug-ins to return the <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MDagPath\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_dag_path.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_1_1_m_dag_path.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MDagPath</a></span> object corresponding to the given <span class=\'code\'><a href=\"javascript:void(0)\" data-symbol=\"MRenderItem\" class=\"a_multireflink\" data-reflinkdata=\"[{&quot;path&quot;:&quot;cpp_ref/class_m_h_w_render_1_1_m_render_item.html&quot;,&quot;title&quot;:&quot;C++ API Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;},{&quot;path&quot;:&quot;py_ref/class_open_maya_render_1_1_m_render_item.html&quot;,&quot;title&quot;:&quot;Maya Python API 2.0 Reference&quot;,&quot;relpathtoroot&quot;:&quot;../../&quot;}]\">MRenderItem</a></span> provided by Maya viewport selection system, so that DAG objects in the viewport can be selectable.</p></li>\n\
</ul>\n\
<div class=\'section\'><a id=\"maya-developer-kit\"></a><h2 id=\"maya-developer-kit\">Maya Developer Kit</h2></div>\n\
<p>The Developer Kit is available online at Autodesk Exchange at <a href=\'https://apps.exchange.autodesk.com/MAYA/en/Home/Index\' title=\'\' target=\'_blank\'>https://apps.exchange.autodesk.com/MAYA/en/Home/Index</a>.</p>\n\
      <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";